[project]
Name: ft_package
Version: 0.0.1
Summary: A sample test package
Home-page: https://github.com/galambey/ft_package
Author: galambey
Author-email: galambey@42.fr
License: MIT
Location: /home/galambey/...
Requires:
Required-by:
Metadata-Version: 2.1
Installer: pip
Classifiers:
Entry-points: